# Generated by Django 5.1 on 2024-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='账号')),
                ('name', models.CharField(max_length=15, verbose_name='用户名')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('usertype', models.BooleanField(choices=[(False, '乘客'), (True, '司机')], verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
