# Generated by Django 5.1 on 2024-08-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户登录', 'verbose_name_plural': '用户登录'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
