# Generated by Django 5.1 on 2024-08-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '账号管理', 'verbose_name_plural': '账号管理'},
        ),
    ]
