# Generated by Django 5.1 on 2024-08-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
