# Generated by Django 5.1 on 2024-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.CharField(default='暂未设置', max_length=500, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='暂未设置', max_length=5, null=True, verbose_name='姓名'),
        ),
    ]
