# Generated by Django 5.1 on 2024-08-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_detail_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
    ]
