# Generated by Django 5.1 on 2024-08-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(default='default', max_length=30, verbose_name='头像'),
        ),
    ]
