# Generated by Django 5.1 on 2024-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='/photo/default.jpg', null=True, upload_to='photo/'),
        ),
    ]
