# Generated by Django 5.1 on 2024-08-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=5)),
                ('driver', models.CharField(max_length=5)),
                ('startlocation', models.CharField(max_length=20)),
                ('start_build', models.CharField(max_length=10)),
                ('endlocation', models.CharField(max_length=20)),
                ('end_build', models.CharField(max_length=10)),
                ('money', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
            },
        ),
    ]
