# Generated by Django 5.1 on 2024-08-15 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_build',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_build',
        ),
        migrations.AddField(
            model_name='order',
            name='endtime',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.IntegerField(choices=[(0, '接单前'), (1, '接客前'), (2, '结单前'), (3, '已结束')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='starttime',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.CharField(max_length=15),
        ),
    ]
