# Generated by Django 5.1 on 2024-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_end_build_remove_order_start_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='endtime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.IntegerField(choices=[(0, '接单前'), (1, '接客前'), (2, '结单前'), (3, '已结束')], default=0),
        ),
    ]
