# Generated by Django 5.1 on 2024-08-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_driver_alter_order_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
