# Generated by Django 5.1 on 2024-08-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_end_order_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
