# Generated by Django 5.1 on 2024-08-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
