# Generated by Django 5.1 on 2024-08-31 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_distance_alter_order_money_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='score',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='money',
            new_name='tolls',
        ),
    ]
